openapi: 3.0.0
info:
    title: mocks
    version: api.keploy.io/v1beta1
    description: Http
servers:
    - url: temp
paths:
    /add:
        post:
            summary: Auto-generated operation
            description: Auto-generated from custom format
            parameters:
                - name: Content-Type
                  in: header
                  required: true
                  schema:
                    type: string
                  example: application/json
                - name: Origin
                  in: header
                  required: true
                  schema:
                    type: string
                  example: http://localhost:5173
                - name: Referer
                  in: header
                  required: true
                  schema:
                    type: string
                  example: http://localhost:5173/
                - name: Sec-Fetch-Dest
                  in: header
                  required: true
                  schema:
                    type: string
                  example: empty
                - name: Accept
                  in: header
                  required: true
                  schema:
                    type: string
                  example: application/json, text/plain, */*
                - name: Accept-Language
                  in: header
                  required: true
                  schema:
                    type: string
                  example: en-US
                - name: Sec-Ch-Ua
                  in: header
                  required: true
                  schema:
                    type: string
                  example: '"Not)A;Brand";v="8", "Chromium";v="138", "HeadlessChrome";v="138"'
                - name: Sec-Ch-Ua-Platform
                  in: header
                  required: true
                  schema:
                    type: string
                  example: '"macOS"'
                - name: Sec-Fetch-Mode
                  in: header
                  required: true
                  schema:
                    type: string
                  example: cors
                - name: Sec-Ch-Ua-Mobile
                  in: header
                  required: true
                  schema:
                    type: string
                  example: ?0
                - name: Sec-Fetch-Site
                  in: header
                  required: true
                  schema:
                    type: string
                  example: same-site
                - name: Accept-Encoding
                  in: header
                  required: true
                  schema:
                    type: string
                  example: gzip, deflate, br, zstd
                - name: Connection
                  in: header
                  required: true
                  schema:
                    type: string
                  example: keep-alive
                - name: Content-Length
                  in: header
                  required: true
                  schema:
                    type: string
                  example: "102"
                - name: User-Agent
                  in: header
                  required: true
                  schema:
                    type: string
                  example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/138.0.7204.23 Safari/537.36
            operationId: 924761ebebcbb2899a86957c6ab0dcea-20250706153033
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                YourQuote:
                                    type: string
                                githubUsername:
                                    type: string
                                name:
                                    type: string
                        example:
                            YourQuote: Testing full flow
                            githubUsername: flowtest123
                            name: Flow Test User 1751795985736
            responses:
                "200":
                    description: 200 OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    data:
                                        properties:
                                            YourQuote:
                                                type: string
                                            githubUsername:
                                                type: string
                                            name:
                                                type: string
                                        type: object
                                    message:
                                        type: string
                                    success:
                                        type: boolean
                            example:
                                data:
                                    YourQuote: Testing full flow
                                    githubUsername: flowtest123
                                    name: Flow Test User 1751795985736
                                message: User added successfully
                                success: true
        options:
            summary: CORS preflight request
            description: Auto-generated CORS preflight operation
            parameters:
                - name: Origin
                  in: header
                  required: true
                  schema:
                    type: string
                  example: http://localhost:5173
                - name: Referer
                  in: header
                  required: true
                  schema:
                    type: string
                  example: http://localhost:5173/
                - name: Sec-Fetch-Dest
                  in: header
                  required: true
                  schema:
                    type: string
                  example: empty
                - name: User-Agent
                  in: header
                  required: true
                  schema:
                    type: string
                  example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/138.0.7204.23 Safari/537.36
                - name: Accept
                  in: header
                  required: true
                  schema:
                    type: string
                  example: '*/*'
                - name: Accept-Encoding
                  in: header
                  required: true
                  schema:
                    type: string
                  example: gzip, deflate, br, zstd
                - name: Access-Control-Request-Headers
                  in: header
                  required: true
                  schema:
                    type: string
                  example: content-type
                - name: Connection
                  in: header
                  required: true
                  schema:
                    type: string
                  example: keep-alive
                - name: Sec-Fetch-Mode
                  in: header
                  required: true
                  schema:
                    type: string
                  example: cors
                - name: Sec-Fetch-Site
                  in: header
                  required: true
                  schema:
                    type: string
                  example: same-site
                - name: Access-Control-Request-Method
                  in: header
                  required: true
                  schema:
                    type: string
                  example: POST
            operationId: 814281aa6f49df1163716edd13abe3e1-20250706153033
            responses:
                "204":
                    description: 204 No Content
                    content:
                        application/json:
                            schema:
                                type: object
                                properties: {}
                            example: {}
    /delete/:id:
        post:
            summary: Auto-generated operation
            description: Auto-generated from custom format
            parameters:
                - name: Connection
                  in: header
                  required: true
                  schema:
                    type: string
                  example: keep-alive
                - name: Content-Length
                  in: header
                  required: true
                  schema:
                    type: string
                  example: "33"
                - name: Content-Type
                  in: header
                  required: true
                  schema:
                    type: string
                  example: application/json
                - name: Origin
                  in: header
                  required: true
                  schema:
                    type: string
                  example: http://localhost:5173
                - name: User-Agent
                  in: header
                  required: true
                  schema:
                    type: string
                  example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/138.0.7204.23 Safari/537.36
                - name: Accept
                  in: header
                  required: true
                  schema:
                    type: string
                  example: application/json, text/plain, */*
                - name: Accept-Language
                  in: header
                  required: true
                  schema:
                    type: string
                  example: en-US
                - name: Referer
                  in: header
                  required: true
                  schema:
                    type: string
                  example: http://localhost:5173/
                - name: Accept-Encoding
                  in: header
                  required: true
                  schema:
                    type: string
                  example: gzip, deflate, br, zstd
                - name: Sec-Ch-Ua-Mobile
                  in: header
                  required: true
                  schema:
                    type: string
                  example: ?0
                - name: Sec-Ch-Ua-Platform
                  in: header
                  required: true
                  schema:
                    type: string
                  example: '"macOS"'
                - name: Sec-Fetch-Site
                  in: header
                  required: true
                  schema:
                    type: string
                  example: same-site
                - name: Sec-Ch-Ua
                  in: header
                  required: true
                  schema:
                    type: string
                  example: '"Not)A;Brand";v="8", "Chromium";v="138", "HeadlessChrome";v="138"'
                - name: Sec-Fetch-Dest
                  in: header
                  required: true
                  schema:
                    type: string
                  example: empty
                - name: Sec-Fetch-Mode
                  in: header
                  required: true
                  schema:
                    type: string
                  example: cors
            operationId: 904cd5cae54be159235422b77f909e38-20250706153033
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                id:
                                    type: string
                        example:
                            id: 686a491179dcf6d2949a7c04
            responses:
                "200":
                    description: 200 OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: string
                                    message:
                                        type: string
                                    success:
                                        type: boolean
                            example:
                                id: 686a491179dcf6d2949a7c04
                                message: User deleted successfully
                                success: true
        options:
            summary: CORS preflight request
            description: Auto-generated CORS preflight operation
            parameters:
                - name: Accept-Encoding
                  in: header
                  required: true
                  schema:
                    type: string
                  example: gzip, deflate, br, zstd
                - name: Access-Control-Request-Method
                  in: header
                  required: true
                  schema:
                    type: string
                  example: POST
                - name: Origin
                  in: header
                  required: true
                  schema:
                    type: string
                  example: http://localhost:5173
                - name: Sec-Fetch-Dest
                  in: header
                  required: true
                  schema:
                    type: string
                  example: empty
                - name: User-Agent
                  in: header
                  required: true
                  schema:
                    type: string
                  example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/138.0.7204.23 Safari/537.36
                - name: Accept
                  in: header
                  required: true
                  schema:
                    type: string
                  example: '*/*'
                - name: Access-Control-Request-Headers
                  in: header
                  required: true
                  schema:
                    type: string
                  example: content-type
                - name: Connection
                  in: header
                  required: true
                  schema:
                    type: string
                  example: keep-alive
                - name: Referer
                  in: header
                  required: true
                  schema:
                    type: string
                  example: http://localhost:5173/
                - name: Sec-Fetch-Mode
                  in: header
                  required: true
                  schema:
                    type: string
                  example: cors
                - name: Sec-Fetch-Site
                  in: header
                  required: true
                  schema:
                    type: string
                  example: same-site
            operationId: 8faa9c0b3f62838fa1b39acaec355f94-20250706153033
            responses:
                "204":
                    description: 204 No Content
                    content:
                        application/json:
                            schema:
                                type: object
                                properties: {}
                            example: {}
    /edit/:id:
        get:
            summary: Auto-generated operation
            description: Auto-generated from custom format
            parameters:
                - name: Accept-Encoding
                  in: header
                  required: true
                  schema:
                    type: string
                  example: gzip, deflate, br, zstd
                - name: Connection
                  in: header
                  required: true
                  schema:
                    type: string
                  example: keep-alive
                - name: Referer
                  in: header
                  required: true
                  schema:
                    type: string
                  example: http://localhost:5173/
                - name: Sec-Ch-Ua
                  in: header
                  required: true
                  schema:
                    type: string
                  example: '"Not)A;Brand";v="8", "Chromium";v="138", "HeadlessChrome";v="138"'
                - name: Sec-Fetch-Mode
                  in: header
                  required: true
                  schema:
                    type: string
                  example: cors
                - name: Sec-Fetch-Site
                  in: header
                  required: true
                  schema:
                    type: string
                  example: same-site
                - name: User-Agent
                  in: header
                  required: true
                  schema:
                    type: string
                  example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/138.0.7204.23 Safari/537.36
                - name: Accept
                  in: header
                  required: true
                  schema:
                    type: string
                  example: application/json, text/plain, */*
                - name: Accept-Language
                  in: header
                  required: true
                  schema:
                    type: string
                  example: en-US
                - name: Origin
                  in: header
                  required: true
                  schema:
                    type: string
                  example: http://localhost:5173
                - name: Sec-Ch-Ua-Mobile
                  in: header
                  required: true
                  schema:
                    type: string
                  example: ?0
                - name: Sec-Ch-Ua-Platform
                  in: header
                  required: true
                  schema:
                    type: string
                  example: '"macOS"'
                - name: Sec-Fetch-Dest
                  in: header
                  required: true
                  schema:
                    type: string
                  example: empty
            operationId: 6282704a52f327be4eead44048c838ce-20250706153033
            responses:
                "200":
                    description: 200 OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    data:
                                        properties:
                                            __v:
                                                type: number
                                            _id:
                                                type: string
                                            YourQuote:
                                                type: string
                                            githubUsername:
                                                type: string
                                            name:
                                                type: string
                                        type: object
                                    message:
                                        type: string
                                    success:
                                        type: boolean
                            example:
                                data:
                                    __v: 0
                                    _id: 686a491179dcf6d2949a7c04
                                    YourQuote: Testing full flow
                                    githubUsername: flowtest123
                                    name: Flow Test User 1751795985736
                                message: User found successfully
                                success: true
        post:
            summary: Auto-generated operation
            description: Auto-generated from custom format
            parameters:
                - name: Accept-Encoding
                  in: header
                  required: true
                  schema:
                    type: string
                  example: gzip, deflate, br, zstd
                - name: Connection
                  in: header
                  required: true
                  schema:
                    type: string
                  example: keep-alive
                - name: Sec-Ch-Ua
                  in: header
                  required: true
                  schema:
                    type: string
                  example: '"Not)A;Brand";v="8", "Chromium";v="138", "HeadlessChrome";v="138"'
                - name: Sec-Fetch-Mode
                  in: header
                  required: true
                  schema:
                    type: string
                  example: cors
                - name: Sec-Ch-Ua-Mobile
                  in: header
                  required: true
                  schema:
                    type: string
                  example: ?0
                - name: User-Agent
                  in: header
                  required: true
                  schema:
                    type: string
                  example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/138.0.7204.23 Safari/537.36
                - name: Accept
                  in: header
                  required: true
                  schema:
                    type: string
                  example: application/json, text/plain, */*
                - name: Accept-Language
                  in: header
                  required: true
                  schema:
                    type: string
                  example: en-US
                - name: Content-Type
                  in: header
                  required: true
                  schema:
                    type: string
                  example: application/json
                - name: Sec-Fetch-Site
                  in: header
                  required: true
                  schema:
                    type: string
                  example: same-site
                - name: Content-Length
                  in: header
                  required: true
                  schema:
                    type: string
                  example: "151"
                - name: Origin
                  in: header
                  required: true
                  schema:
                    type: string
                  example: http://localhost:5173
                - name: Referer
                  in: header
                  required: true
                  schema:
                    type: string
                  example: http://localhost:5173/
                - name: Sec-Ch-Ua-Platform
                  in: header
                  required: true
                  schema:
                    type: string
                  example: '"macOS"'
                - name: Sec-Fetch-Dest
                  in: header
                  required: true
                  schema:
                    type: string
                  example: empty
            operationId: e8ce4d40259ec2358bd1f3edaaa1aa97-20250706153033
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                __v:
                                    type: number
                                _id:
                                    type: string
                                YourQuote:
                                    type: string
                                githubUsername:
                                    type: string
                                name:
                                    type: string
                        example:
                            __v: 0
                            _id: 686a491179dcf6d2949a7c04
                            YourQuote: Testing full flow
                            githubUsername: flowtest123
                            name: Flow Test User 1751795985736 Updated
            responses:
                "200":
                    description: 200 OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    data:
                                        properties:
                                            __v:
                                                type: number
                                            _id:
                                                type: string
                                            YourQuote:
                                                type: string
                                            githubUsername:
                                                type: string
                                            name:
                                                type: string
                                        type: object
                                    message:
                                        type: string
                                    success:
                                        type: boolean
                            example:
                                data:
                                    __v: 0
                                    _id: 686a491179dcf6d2949a7c04
                                    YourQuote: Testing full flow
                                    githubUsername: flowtest123
                                    name: Flow Test User 1751795985736
                                message: User updated successfully
                                success: true
        options:
            summary: CORS preflight request
            description: Auto-generated CORS preflight operation
            parameters:
                - name: Connection
                  in: header
                  required: true
                  schema:
                    type: string
                  example: keep-alive
                - name: Sec-Fetch-Dest
                  in: header
                  required: true
                  schema:
                    type: string
                  example: empty
                - name: Accept
                  in: header
                  required: true
                  schema:
                    type: string
                  example: '*/*'
                - name: Accept-Encoding
                  in: header
                  required: true
                  schema:
                    type: string
                  example: gzip, deflate, br, zstd
                - name: Origin
                  in: header
                  required: true
                  schema:
                    type: string
                  example: http://localhost:5173
                - name: Referer
                  in: header
                  required: true
                  schema:
                    type: string
                  example: http://localhost:5173/
                - name: Sec-Fetch-Mode
                  in: header
                  required: true
                  schema:
                    type: string
                  example: cors
                - name: Sec-Fetch-Site
                  in: header
                  required: true
                  schema:
                    type: string
                  example: same-site
                - name: User-Agent
                  in: header
                  required: true
                  schema:
                    type: string
                  example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/138.0.7204.23 Safari/537.36
                - name: Access-Control-Request-Headers
                  in: header
                  required: true
                  schema:
                    type: string
                  example: content-type
                - name: Access-Control-Request-Method
                  in: header
                  required: true
                  schema:
                    type: string
                  example: POST
            operationId: 9a45613748fb61b88c228c67ab35f365-20250706153033
            responses:
                "204":
                    description: 204 No Content
                    content:
                        application/json:
                            schema:
                                type: object
                                properties: {}
                            example: {}
    /read:
        get:
            summary: Auto-generated operation
            description: Auto-generated from custom format
            parameters:
                - name: Sec-Ch-Ua-Platform
                  in: header
                  required: true
                  schema:
                    type: string
                  example: '"macOS"'
                - name: Sec-Fetch-Dest
                  in: header
                  required: true
                  schema:
                    type: string
                  example: empty
                - name: Sec-Fetch-Mode
                  in: header
                  required: true
                  schema:
                    type: string
                  example: cors
                - name: Accept
                  in: header
                  required: true
                  schema:
                    type: string
                  example: application/json, text/plain, */*
                - name: Accept-Language
                  in: header
                  required: true
                  schema:
                    type: string
                  example: en-US
                - name: Referer
                  in: header
                  required: true
                  schema:
                    type: string
                  example: http://localhost:5173/
                - name: Sec-Fetch-Site
                  in: header
                  required: true
                  schema:
                    type: string
                  example: same-site
                - name: User-Agent
                  in: header
                  required: true
                  schema:
                    type: string
                  example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/138.0.7204.23 Safari/537.36
                - name: Accept-Encoding
                  in: header
                  required: true
                  schema:
                    type: string
                  example: gzip, deflate, br, zstd
                - name: Connection
                  in: header
                  required: true
                  schema:
                    type: string
                  example: keep-alive
                - name: Origin
                  in: header
                  required: true
                  schema:
                    type: string
                  example: http://localhost:5173
                - name: Sec-Ch-Ua
                  in: header
                  required: true
                  schema:
                    type: string
                  example: '"Not)A;Brand";v="8", "Chromium";v="138", "HeadlessChrome";v="138"'
                - name: Sec-Ch-Ua-Mobile
                  in: header
                  required: true
                  schema:
                    type: string
                  example: ?0
            operationId: 6381affa85781eb70bddce028192c972-20250706153033
            responses:
                "200":
                    description: 200 OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    data:
                                        items:
                                            properties:
                                                __v:
                                                    type: number
                                                _id:
                                                    type: string
                                                YourQuote:
                                                    type: string
                                                githubUsername:
                                                    type: string
                                                name:
                                                    type: string
                                            type: object
                                        type: array
                                    message:
                                        type: string
                                    success:
                                        type: boolean
                            example:
                                data:
                                    - __v: 0
                                      _id: 686773ab676b8c8532ae2da3
                                      YourQuote: This is a test quote
                                      githubUsername: testuser123
                                      name: Test User
                                    - __v: 0
                                      _id: 6867f605798e98fd56b6b170
                                      YourQuote: This is a test quote
                                      githubUsername: testuser123
                                      name: Test User
                                    - __v: 0
                                      _id: 6867f8cac5ee261f2ef0e903
                                      YourQuote: This is a test quote
                                      githubUsername: testuser123
                                      name: Test User
                                    - __v: 0
                                      _id: 6867fc079b271a8b6aea9699
                                      YourQuote: This is a test quote
                                      githubUsername: testuser123
                                      name: Test User
                                    - __v: 0
                                      _id: 6867fd7af0988f5fea8b5a48
                                      YourQuote: This is a test quote
                                      githubUsername: testuser123
                                      name: Test User
                                    - __v: 0
                                      _id: 6867fe4a3b0e9dde098a8c44
                                      YourQuote: This is a test quote
                                      githubUsername: testuser123
                                      name: Test User
                                    - __v: 0
                                      _id: 686802139ad73114af3e8810
                                      YourQuote: This is a test quote
                                      githubUsername: testuser123
                                      name: Test User
                                    - __v: 0
                                      _id: 686803ea3632090141606ad1
                                      YourQuote: This is a test quote
                                      githubUsername: testuser123
                                      name: Test User
                                    - __v: 0
                                      _id: 686805a7b02d2a26984c8155
                                      YourQuote: This is a test quote
                                      githubUsername: testuser123
                                      name: Test User
                                    - __v: 0
                                      _id: 686809b4ce6facc4a80a167a
                                      YourQuote: This is a test quote
                                      githubUsername: testuser123
                                      name: Test User
                                    - __v: 0
                                      _id: 68680c50a6e2b60538580c12
                                      YourQuote: This is a test quote
                                      githubUsername: testuser123
                                      name: Test User
                                    - __v: 0
                                      _id: 68680c7fa6e2b60538580c15
                                      YourQuote: This is a test quote
                                      githubUsername: testuser123
                                      name: Test User
                                    - __v: 0
                                      _id: 686a418d983390276f3627d5
                                      YourQuote: This is a test quote
                                      githubUsername: testuser123
                                      name: Test User
                                    - __v: 0
                                      _id: 686a490879dcf6d2949a7bfa
                                      YourQuote: This is a test quote
                                      githubUsername: testuser123
                                      name: Test User
                                message: Users fetched successfully
                                success: true
components: {}
