openapi: 3.0.0
info:
    title: mocks
    version: api.keploy.io/v1beta1
    description: Http
servers:
    - url: temp
paths:
    /add:
        post:
            summary: Auto-generated operation
            description: Auto-generated from custom format
            parameters:
                - name: Accept-Language
                  in: header
                  required: true
                  schema:
                    type: string
                  example: en-US
                - name: Content-Length
                  in: header
                  required: true
                  schema:
                    type: string
                  example: "102"
                - name: Origin
                  in: header
                  required: true
                  schema:
                    type: string
                  example: http://localhost:5173
                - name: Sec-Ch-Ua-Platform
                  in: header
                  required: true
                  schema:
                    type: string
                  example: '"macOS"'
                - name: Sec-Fetch-Site
                  in: header
                  required: true
                  schema:
                    type: string
                  example: same-site
                - name: Accept
                  in: header
                  required: true
                  schema:
                    type: string
                  example: application/json, text/plain, */*
                - name: Sec-Fetch-Mode
                  in: header
                  required: true
                  schema:
                    type: string
                  example: cors
                - name: Accept-Encoding
                  in: header
                  required: true
                  schema:
                    type: string
                  example: gzip, deflate, br, zstd
                - name: Referer
                  in: header
                  required: true
                  schema:
                    type: string
                  example: http://localhost:5173/
                - name: Sec-Ch-Ua
                  in: header
                  required: true
                  schema:
                    type: string
                  example: '"Not)A;Brand";v="8", "Chromium";v="138", "HeadlessChrome";v="138"'
                - name: Sec-Ch-Ua-Mobile
                  in: header
                  required: true
                  schema:
                    type: string
                  example: ?0
                - name: Sec-Fetch-Dest
                  in: header
                  required: true
                  schema:
                    type: string
                  example: empty
                - name: Connection
                  in: header
                  required: true
                  schema:
                    type: string
                  example: keep-alive
                - name: Content-Type
                  in: header
                  required: true
                  schema:
                    type: string
                  example: application/json
                - name: User-Agent
                  in: header
                  required: true
                  schema:
                    type: string
                  example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/138.0.7204.23 Safari/537.36
            operationId: f8629f14597e1269130ad64159a61568-20250704225716
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties: {}
                        example: {}
            responses:
                "200":
                    description: 200 OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    data:
                                        properties:
                                            YourQuote:
                                                type: string
                                            githubUsername:
                                                type: string
                                            name:
                                                type: string
                                        type: object
                                    message:
                                        type: string
                                    success:
                                        type: boolean
                            example:
                                data:
                                    YourQuote: Testing full flow
                                    githubUsername: flowtest123
                                    name: Flow Test User 1751649416762
                                message: User added successfully
                                success: true
    /delete/:id:
        post:
            summary: Auto-generated operation
            description: Auto-generated from custom format
            parameters:
                - name: Sec-Ch-Ua-Platform
                  in: header
                  required: true
                  schema:
                    type: string
                  example: '"macOS"'
                - name: User-Agent
                  in: header
                  required: true
                  schema:
                    type: string
                  example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/138.0.7204.23 Safari/537.36
                - name: Accept-Encoding
                  in: header
                  required: true
                  schema:
                    type: string
                  example: gzip, deflate, br, zstd
                - name: Connection
                  in: header
                  required: true
                  schema:
                    type: string
                  example: keep-alive
                - name: Sec-Ch-Ua
                  in: header
                  required: true
                  schema:
                    type: string
                  example: '"Not)A;Brand";v="8", "Chromium";v="138", "HeadlessChrome";v="138"'
                - name: Sec-Ch-Ua-Mobile
                  in: header
                  required: true
                  schema:
                    type: string
                  example: ?0
                - name: Sec-Fetch-Mode
                  in: header
                  required: true
                  schema:
                    type: string
                  example: cors
                - name: Accept-Language
                  in: header
                  required: true
                  schema:
                    type: string
                  example: en-US
                - name: Sec-Fetch-Dest
                  in: header
                  required: true
                  schema:
                    type: string
                  example: empty
                - name: Sec-Fetch-Site
                  in: header
                  required: true
                  schema:
                    type: string
                  example: same-site
                - name: Accept
                  in: header
                  required: true
                  schema:
                    type: string
                  example: application/json, text/plain, */*
                - name: Content-Type
                  in: header
                  required: true
                  schema:
                    type: string
                  example: application/json
                - name: Referer
                  in: header
                  required: true
                  schema:
                    type: string
                  example: http://localhost:5173/
                - name: Content-Length
                  in: header
                  required: true
                  schema:
                    type: string
                  example: "33"
                - name: Origin
                  in: header
                  required: true
                  schema:
                    type: string
                  example: http://localhost:5173
            operationId: 9a902581be2dae823035433d2c80833a-20250704225716
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties: {}
                        example: {}
            responses:
                "200":
                    description: 200 OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: string
                                    message:
                                        type: string
                                    success:
                                        type: boolean
                            example:
                                id: 68680c88a6e2b60538580c1f
                                message: User deleted successfully
                                success: true
    /edit/:id:
        get:
            summary: Auto-generated operation
            description: Auto-generated from custom format
            parameters:
                - name: Sec-Ch-Ua-Mobile
                  in: header
                  required: true
                  schema:
                    type: string
                  example: ?0
                - name: Sec-Fetch-Dest
                  in: header
                  required: true
                  schema:
                    type: string
                  example: empty
                - name: Accept
                  in: header
                  required: true
                  schema:
                    type: string
                  example: application/json, text/plain, */*
                - name: Accept-Encoding
                  in: header
                  required: true
                  schema:
                    type: string
                  example: gzip, deflate, br, zstd
                - name: Origin
                  in: header
                  required: true
                  schema:
                    type: string
                  example: http://localhost:5173
                - name: Referer
                  in: header
                  required: true
                  schema:
                    type: string
                  example: http://localhost:5173/
                - name: Sec-Ch-Ua-Platform
                  in: header
                  required: true
                  schema:
                    type: string
                  example: '"macOS"'
                - name: Sec-Fetch-Mode
                  in: header
                  required: true
                  schema:
                    type: string
                  example: cors
                - name: Sec-Fetch-Site
                  in: header
                  required: true
                  schema:
                    type: string
                  example: same-site
                - name: User-Agent
                  in: header
                  required: true
                  schema:
                    type: string
                  example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/138.0.7204.23 Safari/537.36
                - name: Accept-Language
                  in: header
                  required: true
                  schema:
                    type: string
                  example: en-US
                - name: Connection
                  in: header
                  required: true
                  schema:
                    type: string
                  example: keep-alive
                - name: Sec-Ch-Ua
                  in: header
                  required: true
                  schema:
                    type: string
                  example: '"Not)A;Brand";v="8", "Chromium";v="138", "HeadlessChrome";v="138"'
            operationId: d76ab6729f8855cd2e1677ac61deaff5-20250704225716
            responses:
                "200":
                    description: 200 OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    data:
                                        properties:
                                            __v:
                                                type: number
                                            _id:
                                                type: string
                                            YourQuote:
                                                type: string
                                            githubUsername:
                                                type: string
                                            name:
                                                type: string
                                        type: object
                                    message:
                                        type: string
                                    success:
                                        type: boolean
                            example:
                                data:
                                    __v: 0
                                    _id: 68680c88a6e2b60538580c1f
                                    YourQuote: Testing full flow
                                    githubUsername: flowtest123
                                    name: Flow Test User 1751649416762
                                message: User found successfully
                                success: true
        post:
            summary: Auto-generated operation
            description: Auto-generated from custom format
            parameters:
                - name: Content-Length
                  in: header
                  required: true
                  schema:
                    type: string
                  example: "151"
                - name: Referer
                  in: header
                  required: true
                  schema:
                    type: string
                  example: http://localhost:5173/
                - name: Sec-Ch-Ua
                  in: header
                  required: true
                  schema:
                    type: string
                  example: '"Not)A;Brand";v="8", "Chromium";v="138", "HeadlessChrome";v="138"'
                - name: Sec-Fetch-Site
                  in: header
                  required: true
                  schema:
                    type: string
                  example: same-site
                - name: Accept
                  in: header
                  required: true
                  schema:
                    type: string
                  example: application/json, text/plain, */*
                - name: Connection
                  in: header
                  required: true
                  schema:
                    type: string
                  example: keep-alive
                - name: Content-Type
                  in: header
                  required: true
                  schema:
                    type: string
                  example: application/json
                - name: Origin
                  in: header
                  required: true
                  schema:
                    type: string
                  example: http://localhost:5173
                - name: Sec-Ch-Ua-Mobile
                  in: header
                  required: true
                  schema:
                    type: string
                  example: ?0
                - name: Sec-Fetch-Dest
                  in: header
                  required: true
                  schema:
                    type: string
                  example: empty
                - name: Accept-Encoding
                  in: header
                  required: true
                  schema:
                    type: string
                  example: gzip, deflate, br, zstd
                - name: Accept-Language
                  in: header
                  required: true
                  schema:
                    type: string
                  example: en-US
                - name: Sec-Ch-Ua-Platform
                  in: header
                  required: true
                  schema:
                    type: string
                  example: '"macOS"'
                - name: Sec-Fetch-Mode
                  in: header
                  required: true
                  schema:
                    type: string
                  example: cors
                - name: User-Agent
                  in: header
                  required: true
                  schema:
                    type: string
                  example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/138.0.7204.23 Safari/537.36
            operationId: 3c058399d82606f4b6c044a08a0dd7a6-20250704225716
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties: {}
                        example: {}
            responses:
                "200":
                    description: 200 OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    data:
                                        properties:
                                            __v:
                                                type: number
                                            _id:
                                                type: string
                                            YourQuote:
                                                type: string
                                            githubUsername:
                                                type: string
                                            name:
                                                type: string
                                        type: object
                                    message:
                                        type: string
                                    success:
                                        type: boolean
                            example:
                                data:
                                    __v: 0
                                    _id: 68680c88a6e2b60538580c1f
                                    YourQuote: Testing full flow
                                    githubUsername: flowtest123
                                    name: Flow Test User 1751649416762
                                message: User updated successfully
                                success: true
    /read:
        get:
            summary: Auto-generated operation
            description: Auto-generated from custom format
            parameters:
                - name: Origin
                  in: header
                  required: true
                  schema:
                    type: string
                  example: http://localhost:5173
                - name: Referer
                  in: header
                  required: true
                  schema:
                    type: string
                  example: http://localhost:5173/
                - name: Sec-Ch-Ua
                  in: header
                  required: true
                  schema:
                    type: string
                  example: '"Not)A;Brand";v="8", "Chromium";v="138", "HeadlessChrome";v="138"'
                - name: Sec-Ch-Ua-Mobile
                  in: header
                  required: true
                  schema:
                    type: string
                  example: ?0
                - name: Sec-Fetch-Dest
                  in: header
                  required: true
                  schema:
                    type: string
                  example: empty
                - name: Connection
                  in: header
                  required: true
                  schema:
                    type: string
                  example: keep-alive
                - name: Sec-Ch-Ua-Platform
                  in: header
                  required: true
                  schema:
                    type: string
                  example: '"macOS"'
                - name: Sec-Fetch-Mode
                  in: header
                  required: true
                  schema:
                    type: string
                  example: cors
                - name: Sec-Fetch-Site
                  in: header
                  required: true
                  schema:
                    type: string
                  example: same-site
                - name: User-Agent
                  in: header
                  required: true
                  schema:
                    type: string
                  example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/138.0.7204.23 Safari/537.36
                - name: Accept
                  in: header
                  required: true
                  schema:
                    type: string
                  example: application/json, text/plain, */*
                - name: Accept-Encoding
                  in: header
                  required: true
                  schema:
                    type: string
                  example: gzip, deflate, br, zstd
                - name: Accept-Language
                  in: header
                  required: true
                  schema:
                    type: string
                  example: en-US
            operationId: 581357d859505711b16444bc2815726b-20250704225716
            responses:
                "200":
                    description: 200 OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    data:
                                        items:
                                            properties:
                                                __v:
                                                    type: number
                                                _id:
                                                    type: string
                                                YourQuote:
                                                    type: string
                                                githubUsername:
                                                    type: string
                                                name:
                                                    type: string
                                            type: object
                                        type: array
                                    message:
                                        type: string
                                    success:
                                        type: boolean
                            example:
                                data:
                                    - __v: 0
                                      _id: 68676b3759bb64a65220b39b
                                      YourQuote: This is a test quote
                                      githubUsername: testuser123
                                      name: Test User
                                    - __v: 0
                                      _id: 68676dab20c4ea6d0b39e3ba
                                      YourQuote: This is a test quote
                                      githubUsername: testuser123
                                      name: Test User
                                    - __v: 0
                                      _id: 686773ab676b8c8532ae2da3
                                      YourQuote: This is a test quote
                                      githubUsername: testuser123
                                      name: Test User
                                    - __v: 0
                                      _id: 6867f605798e98fd56b6b170
                                      YourQuote: This is a test quote
                                      githubUsername: testuser123
                                      name: Test User
                                    - __v: 0
                                      _id: 6867f8cac5ee261f2ef0e903
                                      YourQuote: This is a test quote
                                      githubUsername: testuser123
                                      name: Test User
                                    - __v: 0
                                      _id: 6867fc079b271a8b6aea9699
                                      YourQuote: This is a test quote
                                      githubUsername: testuser123
                                      name: Test User
                                    - __v: 0
                                      _id: 6867fd7af0988f5fea8b5a48
                                      YourQuote: This is a test quote
                                      githubUsername: testuser123
                                      name: Test User
                                    - __v: 0
                                      _id: 6867fe4a3b0e9dde098a8c44
                                      YourQuote: This is a test quote
                                      githubUsername: testuser123
                                      name: Test User
                                    - __v: 0
                                      _id: 686802139ad73114af3e8810
                                      YourQuote: This is a test quote
                                      githubUsername: testuser123
                                      name: Test User
                                    - __v: 0
                                      _id: 686803ea3632090141606ad1
                                      YourQuote: This is a test quote
                                      githubUsername: testuser123
                                      name: Test User
                                    - __v: 0
                                      _id: 686805a7b02d2a26984c8155
                                      YourQuote: This is a test quote
                                      githubUsername: testuser123
                                      name: Test User
                                    - __v: 0
                                      _id: 686809b4ce6facc4a80a167a
                                      YourQuote: This is a test quote
                                      githubUsername: testuser123
                                      name: Test User
                                    - __v: 0
                                      _id: 68680c50a6e2b60538580c12
                                      YourQuote: This is a test quote
                                      githubUsername: testuser123
                                      name: Test User
                                    - __v: 0
                                      _id: 68680c7fa6e2b60538580c15
                                      YourQuote: This is a test quote
                                      githubUsername: testuser123
                                      name: Test User
                                message: Users fetched successfully
                                success: true
components: {}
